name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Francinette
      run: bash -c "$(curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh)"
      
    - name: Install Norminette
      run: python3 -m pip install --upgrade pip setuptools
           python3 -m pip install norminette
           
    - name: Run tests
      run: ~/francinette/tester.sh
